[package]
name = "logviewer"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9"
tempfile = "3.8"
crossterm = "0.27"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
shlex = "1.3.0"
clap = { version = "4.0", features = ["derive"] }
